Scripts: async, defer
javascript-tutorial/tr.javascript.info pull request #356
Opened 2024-04-30 20:21 UTC by cys27

2024-05-25 10:24 UTC, sahinyanlik commented on 2-ui/5-loading/02-script-async-defer/article.md
> +Modern websitelerinde, genellikle komut dosyaları (scripts), HTML kodlarından daha yoğunluktadır: onların indirme boyutu daha fazla ve işlem süreleri daha uzundur.
Çok bire bir çevirmeye çalışmışsınız.

2024-05-25 10:26 UTC, sahinyanlik commented on 2-ui/5-loading/02-script-async-defer/article.md
> +Tarayıcı HTML'i yüklediği sırada `<script>...</script>` kısmına denk geldiğinde, DOM'u oluşturmaya devam edemeyebilir. Tarayıcı böyle bir durumda script'i çalıştırmak zorundadır. Benzer durum `<scrip
Burada da aynı şeklide çok defa 'Tarayıcı' diyerek başlıyorsunuz. Halbuki bunları her defa yazmanıza gerek yok. Bire bir çeviri yaptığınızda okunması çok zor oluyor. Tekrar gözden geçirebilir misiniz.

2024-05-25 10:30 UTC, sahinyanlik commented on 2-ui/5-loading/02-script-async-defer/article.md
> +Ama onların arasında temel farklılıklar var:
Tekrar okuyup düzeltebilir misiniz?

2024-05-25 10:34 UTC, sahinyanlik requested changes
Merhabalar bir kaç yorum yazdım bunlara göre tekrar düzenleyebilir misiniz?

2024-06-13 15:37 UTC, cys27 commented
/done

2024-06-13 15:41 UTC, cys27 commented
Tekrardan değiştirmemi istediğiniz bir yer varsa yapabilirim. Aynı şekilde Bezier eğrilerinide çevirmiştim ancak ayrı bir pull request oluşturamadım. Otomatik olarak ilk başta, `scripts: async, defer` için açtığım bu pull request'e dahil edilmiş. Haliyle `Turkish Translation Progress` bölümünde Bezier Eğrileri kısmında pull request gözükmüyor.

2024-10-27 03:40 UTC, sahinyanlik approved these changes

2024-10-27 03:40 UTC, merged

2024-10-27 03:40 UTC, sahinyanlik commented
Yardımlarınız için teşekkür ederim.